"""Message Models and Types."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


RoleType = Literal["system", "user", "assistant", "tool"]


class ToolCall(BaseModel):
    """Tool invocation payload."""

    id: str = Field(description="Unique ID of the tool call")
    name: str = Field(description="Name of the tool being called")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Parsed arguments for the tool")


class ToolResult(BaseModel):
    """Result of a tool execution."""

    tool_call_id: str = Field(description="ID matching the ToolCall")
    name: str = Field(description="Name of the tool")
    content: Any = Field(description="Execution result content or output")
    is_error: bool = Field(default=False, description="Whether execution produced an error")


class Message(BaseModel):
    """Unified message model compatible across agent engines."""

    role: RoleType = Field(description="Sender role")
    content: str = Field(description="Textual content of the message")
    name: Optional[str] = Field(default=None, description="Optional name of the agent/tool")
    tool_calls: Optional[List[ToolCall]] = Field(default=None, description="Tool calls generated by assistant")
    tool_results: Optional[List[ToolResult]] = Field(default=None, description="Tool results returned to agent")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary metadata")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
